{% set name = "power-grid-model-io" %}
{% set version = "1.2.77" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/power-grid-model-io-{{ version }}.tar.gz
  sha256: 2bffbdcd74c1e7fa5f0aa8ff85186e7750ce8d2c34c1bc7e792c0c20ecdd863e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.8
    - numpy >=1.20
    - openpyxl
    - pandas
    - power-grid-model >=1.6
    - pyyaml
    - structlog
    - tqdm

test:
  imports:
    - power_grid_model_io
    - power_grid_model_io.converters
  commands:
    - pip check
    - pytest
  source_files:
    - tests
    - pyproject.toml
  requires:
    - pip
    - pytest
    - pytest-cov
    - pydantic
    - pandapower >=2.13.1

about:
  home: https://lfenergy.org/projects/power-grid-model/
  summary: Power Grid Model Input/Output
  license: MPL-2.0
  license_file: LICENSE
  doc_url: https://power-grid-model-io.readthedocs.io
  dev_url: https://github.com/PowerGridModel/power-grid-model-io


extra:
  recipe-maintainers:
    - TonyXiang8787
    - mgovers
    - nitbharambe
    - petersalemink95
