{% set python_min = "3.11" %}
{% set name = "power-grid-model-io" %}
{% set version = "1.3.23" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 68800953cf79b45d4d63c3e522681397addadb79b60b6846cf5ff033c592fffd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=2.0.0
    - openpyxl
    - pandas
    - power-grid-model >=1.6
    - pyyaml
    - structlog
    - tqdm

test:
  imports:
    - power_grid_model_io
    - power_grid_model_io.converters
  commands:
    - pip check
    - pytest
  source_files:
    - tests
    - pyproject.toml
  requires:
    - pip
    - pytest
    - pytest-cov
    - pydantic
    - scipy
    - pandapower >=3.0
    - numpy >=2.0.0
    - python {{ python_min }}

about:
  home: https://lfenergy.org/projects/power-grid-model/
  summary: Power Grid Model Input/Output
  license: MPL-2.0
  license_file: LICENSE
  doc_url: https://power-grid-model-io.readthedocs.io
  dev_url: https://github.com/PowerGridModel/power-grid-model-io


extra:
  recipe-maintainers:
    - figueroa1395
    - TonyXiang8787
    - mgovers
    - nitbharambe
    - petersalemink95
