{% set name = "power-grid-model-io" %}
{% set version = "1.2.101" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: bd86274bcd755b14ca31b42be4eac993c0215af38525089934316443de841eda

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.8
    - numpy >=1.20
    - openpyxl
    - pandas
    - power-grid-model >=1.6
    - pyyaml
    - structlog
    - tqdm

test:
  imports:
    - power_grid_model_io
    - power_grid_model_io.converters
  commands:
    - pip check
    - pytest
  source_files:
    - tests
    - pyproject.toml
  requires:
    - pip
    - pytest
    - pytest-cov
    - pydantic
    - pandapower >=2.13.1
    - numpy >=1.20, <2.0.0

about:
  home: https://lfenergy.org/projects/power-grid-model/
  summary: Power Grid Model Input/Output
  license: MPL-2.0
  license_file: LICENSE
  doc_url: https://power-grid-model-io.readthedocs.io
  dev_url: https://github.com/PowerGridModel/power-grid-model-io


extra:
  recipe-maintainers:
    - figueroa1395
    - TonyXiang8787
    - mgovers
    - nitbharambe
    - petersalemink95
